# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GStreamer-GConf
version:      0.01
version_from: GConf.pm
installdirs:  site
requires:
    ExtUtils::Depends:             0.205
    ExtUtils::PkgConfig:           1.07
    GStreamer:                     0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
